# -*- coding: utf-8 -*-
"""MallCustomerTask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BYfO90NG-XbUbmH_nePsFv8M7eOqO72
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

! pip install kaggle

!kaggle datasets download -d vjchoudhary7/customer-segmentation-tutorial-in-python

df = pd.read_csv('/content/customer-segmentation-tutorial-in-python.zip')
df

df.tail()

df.info()

df.describe()

df.describe().T

df.describe(include='all')

df.isnull().sum()

df.duplicated().sum()

df.shape

df.columns

for i in df.columns:
  print(df[i].value_counts())

df.isna().sum()

df = df.drop(columns = ['CustomerID','Gender','Age'], axis=1).values

df.shape





"""# Kmeans"""



"""# Find the k Using elbow method"""

wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  kmeans.fit(df)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

"""# Train Dataset"""

k_means = KMeans(n_clusters=5, init='k-means++', random_state=42)
y = k_means.fit_predict(df)

k_means.cluster_centers_

"""# visualize the cluster formed"""

plt.figure(figsize=(8,8))
plt.scatter(df[y==0,0], df[y==0,1], s=50, c='red', label='Cluster 1')
plt.scatter(df[y==1,0], df[y==1,1], s=50, c='pink', label='Cluster 2')
plt.scatter(df[y==2,0], df[y==2,1], s=50, c='yellow', label='Cluster 3')
plt.scatter(df[y==3,0], df[y==3,1], s=50, c='green', label='Cluster 4')
plt.scatter(df[y==4,0], df[y==4,1], s=50, c='orange', label='Cluster 5')
plt.scatter(k_means.cluster_centers_[:,0], k_means.cluster_centers_[:,1], s=200, c='maroon', label='Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()